### PR TITLE
Properly assign LED numbers for main repeater virtual leds

### LINKED ISSUE #35: led / component number calculation
https://github.com/thecynic/pylutron/blob/master/pylutron/__init__.py#L282
When `led_num` is calculated from the component number, it assumes that the led number is 80 less than the component number. For the case of the `MAIN_REPEATER` device type, this is not true. Here's a snippet of the LED `ComponentNumber` from my XML: 
```
                          </Preset>
                        </Presets>
                      </Action>
                    </Actions>
                    <Notes />
                  </Button>
                </Component>
                <Component ComponentNumber="101" ComponentType="LED">
                  <LED UUID="133" isReverseLogic="false" ProgrammingModelID="957" />
                </Component>
                <Component ComponentNumber="102" ComponentType="LED">
                  <LED UUID="134" isReverseLogic="false" ProgrammingModelID="9441" />
                </Component>
```
I think we need to do a check to see if we're looking at a `MAIN_REPEATER` device type, and if so, subtract 100 instead of 80. Thoughts? 
CC @thecynic

### PR DESCRIPTION
**Pull request by thecynic**
Fixes #35 

@JonGilmore PTAL

### CODE REVIEW

**Comment by thecynic** [comment]
No clue, none of this is documented, so trial and error :) Whoever has the other types maybe can chime in when things don't work.

**Comment by JonGilmore** [comment]
haha, right on. i check off a few on the list, but not all. I think we can merge this in. Btw, are you on discord? May be easier to chat there to talk about issues and things.

**Comment by thecynic** [comment]
I am on discord, but for video games :) I'd rather not tie real life and pretend life together ;-)

I only have main repeater, seetouch, and pico. Perhaps someone else here who has the other types can try it out, or at least send me their xml files and i can take a look.

**Comment by JonGilmore** [comment]
np man, just hit me up on discord with the same username as GitHub if you want to chat.

**Pull request merged**
